#!/bin/sh

DIR=/home/lars/html/gcc-testresults

echo Content-type: text/html
echo ''
echo '<html><body>'
ls -1 $DIR/$VAR_version | while read i; do
    echo '<a href="/cgi-bin/test2?version='$VAR_version'&target='$i'&tool=gcc">'$i'</a><br>'
done
echo '</body></html>'
exit 0
